# Generated by Django 4.2.3 on 2023-08-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myStore', '0002_product_alter_category_name_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='countProduct',
            field=models.IntegerField(),
        ),
    ]
